### ISSUE TITLE
.

### ISSUE THREAD

**Issue by habib-sadullaev** [TechnoPakCp/m.technopak.uz#11]

**Comment by AshotAdmin** [comment]
Хабиб, поставьте бухгалтерский учет вместо прочего. Уберите дизайн, срок изготовления, продавца.
Но самое главное, чтоб все данные были не редактируемые, кроме предоплаты.

p.s. и это все что вы сделали за полторы недели? Очень надеюсь, что с кодом вы продвинулись гораздо дальше...
